// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The boxcar Authors

//! [`AuditFs`]: a `FileSystem` that records what the guest does to a share
//! and otherwise behaves exactly like the filesystem it wraps.
//!
//! Every request reaches the wrapped filesystem with the guest's
//! credentials squashed to root (`squash`, in `forward`); the
//! guest's own ids go into the record's subject. Replies come back
//! unchanged. The methods that are audited are written out below; every
//! other one is generated by `forward!`.
//!
//! Recording never makes a syscall on the reply path: paths come from the
//! [`PathMap`], and a closed file is hashed later by the [`HashWorker`].
//!
//! What each method records, at [`AuditLevel::Normal`]:
//!
//! | method | event |
//! |---|---|
//! | `init` | `fs.mount`, once per mount |
//! | `lookup` | `fs.denied` (op `lookup`) on EACCES or EPERM; at Verbose also on ENOENT |
//! | `open`, `create` | `fs.open`, `fs.create`, failed or not |
//! | `release` | `fs.close`: hashed if the handle wrote, created or truncated, else `not_hashed` |
//! | `destroy`, and [`AuditFs::shutdown`] or drop | `fs.close` for every handle still open, attributed to its opener |
//! | `unlink`, `rmdir`, `rename`, `mkdir`, `mknod`, `symlink`, `link` | the event of that name |
//! | `setattr`, `fallocate` | `fs.setattr` with the fields set, `fs.fallocate` |
//! | `setxattr`, `removexattr` | `fs.xattr` (op `set`, `remove`) |
//! | `access` | `fs.denied` (op `access`) on EACCES |
//! | `read`, `write`, `readdir`, `readdirplus` | at Verbose only: `fs.read`, `fs.write` (with `attrib`), `fs.readdir`, which may be dropped |
//!
//! `lookup`, `create`, `mkdir`, `mknod`, `symlink`, `link` and each
//! `readdirplus` entry add to the path map, `forget` and `batch_forget`
//! take away, and `rename`, `unlink` and `rmdir` rename and delete in it.
//!
//! `write`, a `setattr` of the size, `fallocate`, `create` and an `open`
//! with `O_TRUNC` move the file's generation (see
//! [`Generations`](crate::hasher)), so a close whose hash is still queued
//! when another handle changes the file is `raced`.
//!
//! Once the audit log has failed (`Events::log_failed`), every method
//! that changes the share (`create`, `write`, `unlink`, `rmdir`, `rename`,
//! `mkdir`, `mknod`, `symlink`, `link`, `setattr`, `fallocate`,
//! `setxattr`, `removexattr`, and an `open` for writing or with `O_TRUNC`)
//! returns EIO without reaching the wrapped filesystem: a change the log
//! cannot record does not happen. Reads, lookups and releases are still
//! served. A log closed cleanly, as the VM stops, refuses nothing.

use std::ffi::{CStr, CString};
use std::io;
use std::os::fd::OwnedFd;
use std::sync::{Arc, PoisonError, RwLock, RwLockReadGuard, RwLockWriteGuard};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use boxcar_audit::AuditSink;
use boxcar_proto::{
    Attrib, FsClose, FsCreate, FsDenied, FsFallocate, FsIo, FsLink, FsMkdir, FsMknod, FsMount,
    FsOpen, FsPathOp, FsRename, FsSetattr, FsSymlink, FsXattr, HashStatus, Payload, SetAttr,
    Subject,
};
use fuse_backend_rs::abi::fuse_abi::{stat64, CreateIn, WRITE_CACHE};
use fuse_backend_rs::api::filesystem::{
    Context, DirEntry, Entry, FileSystem, FsOptions, OpenOptions, SetattrValid, ZeroCopyReader,
    ZeroCopyWriter,
};

use crate::events::{
    c_text, decode_open_flags, errno, is_exec, op_result, realtime_ns, subject, Events,
};
use crate::forward::squash;
use crate::handles::{HandleEntry, HandleTable};
use crate::hasher::{hash_file, FileKey, Generations, HashFn, HashJob, HashWorker};
use crate::path_map::{FileId, PathMap, PathText};
use crate::share::FsShareConfig;

/// `init` options the guest never gets. The write-back cache would let the
/// guest kernel merge and delay writes, so they would reach the host, and
/// the audit, late and attributed to whichever thread flushes them. The DAX
/// bits are refused so the guest does not negotiate per-file DAX, but that
/// alone does not prevent DAX: a guest maps host files only through a
/// shared-memory window the virtio-fs device exposes, and the device must
/// not expose one (the Task 12 device does not). Through such a window
/// reads and writes would bypass FUSE, and this audit, entirely.
const MASKED_OPTIONS: FsOptions = FsOptions::WRITEBACK_CACHE
    .union(FsOptions::MAP_ALIGNMENT)
    .union(FsOptions::PERFILE_DAX);

/// How much is recorded.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum AuditLevel {
    /// Opens, closes, mutations and denials.
    #[default]
    Normal,
    /// Also every read, write and directory listing, and lookups of missing
    /// names.
    Verbose,
}

/// How an [`AuditFs`] records.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct AuditFsOptions {
    pub level: AuditLevel,
    /// Files larger than this are closed without a hash (`skipped_size`).
    pub hash_max_bytes: u64,
}

impl Default for AuditFsOptions {
    /// Normal level, 64 MiB hashing limit.
    fn default() -> Self {
        AuditFsOptions {
            level: AuditLevel::Normal,
            hash_max_bytes: 64 * 1024 * 1024,
        }
    }
}

/// The audited filesystem over `F`, for one share.
pub struct AuditFs<F: FileSystem<Inode = u64, Handle = u64>> {
    inner: F,
    guest_path: String,
    host_root: String,
    cache_policy: &'static str,
    level: AuditLevel,
    paths: RwLock<PathMap>,
    handles: HandleTable,
    events: Arc<Events>,
    hasher: HashWorker,
    generations: Arc<Generations>,
}

impl<F: FileSystem<Inode = u64, Handle = u64>> AuditFs<F> {
    /// Wraps `inner`, which serves `share`. `host_root_fd` is an open
    /// descriptor of the share's host directory, which closed files are
    /// reopened beneath to hash them. Events go to `sink`.
    pub fn new(
        inner: F,
        share: &FsShareConfig,
        host_root_fd: OwnedFd,
        sink: AuditSink,
        opts: AuditFsOptions,
    ) -> Self {
        Self::with_hash(inner, share, host_root_fd, sink, opts, hash_file)
    }

    /// [`new`](Self::new), hashing closed files with `hash`.
    pub(crate) fn with_hash(
        inner: F,
        share: &FsShareConfig,
        host_root_fd: OwnedFd,
        sink: AuditSink,
        opts: AuditFsOptions,
        hash: HashFn,
    ) -> Self {
        let events = Arc::new(Events::new(sink, share.tag.clone()));
        let hasher = HashWorker::with_hash(
            &share.tag,
            host_root_fd,
            opts.hash_max_bytes,
            Arc::clone(&events),
            hash,
        );
        AuditFs {
            inner,
            guest_path: share.guest_path.clone(),
            host_root: share.host_dir.to_string_lossy().into_owned(),
            cache_policy: share.cache.as_str(),
            level: opts.level,
            paths: RwLock::new(PathMap::new()),
            handles: HandleTable::new(),
            events,
            hasher,
            generations: Arc::default(),
        }
    }

    /// Returns once every close queued for hashing has been recorded.
    pub fn flush_hashes(&self) {
        self.hasher.flush();
    }

    /// Starts the hash threads again after [`shutdown`](Self::shutdown)
    /// (a device reset), so that closes are hashed off the FUSE reply path
    /// once more; nothing changes while they run. The device calls it at
    /// every activation.
    pub fn restart_hashing(&self) {
        self.hasher.restart();
    }

    /// How many hash threads are running: 0 after a shutdown, when closes
    /// are hashed on the thread that releases them.
    pub fn hash_threads(&self) -> usize {
        self.hasher.threads_alive()
    }

    /// Closes every handle the guest left open (see `destroy`), records
    /// the closes still being hashed, and stops the hash threads. Dropping
    /// the filesystem does the same. Call it before closing the audit log.
    pub fn shutdown(&self) {
        self.close_open_handles();
        self.hasher.shutdown();
    }

    /// Every inode the path map knows, the root included, ascending.
    pub fn known_inodes(&self) -> Vec<u64> {
        self.read_paths().inodes()
    }

    /// The wrapped filesystem.
    pub fn inner(&self) -> &F {
        &self.inner
    }

    fn read_paths(&self) -> RwLockReadGuard<'_, PathMap> {
        // Every update leaves the map consistent.
        self.paths.read().unwrap_or_else(PoisonError::into_inner)
    }

    fn write_paths(&self) -> RwLockWriteGuard<'_, PathMap> {
        self.paths.write().unwrap_or_else(PoisonError::into_inner)
    }

    fn verbose(&self) -> bool {
        self.level == AuditLevel::Verbose
    }

    /// EIO once the audit log has failed: the change would go unrecorded,
    /// so it is not made (see the module docs).
    fn refuse_if_log_failed(&self) -> io::Result<()> {
        if self.events.log_failed() {
            Err(io::Error::from_raw_os_error(libc::EIO))
        } else {
            Ok(())
        }
    }

    /// The content of `ino` may have changed: a close of it still waiting
    /// for its hash is `raced`.
    fn content_changed(&self, ino: u64) {
        let host = self.read_paths().host_id(ino);
        self.generations.changed(FileKey::of(ino, host));
    }

    /// The path of `ino`, for a record: its text and, for a name that is
    /// not UTF-8, its bytes.
    fn path(&self, ino: u64) -> PathText {
        self.read_paths().path_text(ino)
    }

    /// The path of `name` in `parent`, for a record.
    fn child(&self, parent: u64, name: &CStr) -> PathText {
        self.read_paths().child_text(parent, name.to_bytes())
    }

    /// A reply handed the kernel `entry` as `name` in `parent`.
    fn remember(&self, parent: u64, name: &[u8], entry: &Entry) {
        let mut paths = self.write_paths();
        paths.insert(parent, name, entry.inode);
        paths.set_host_id(entry.inode, host_id(&entry.attr));
    }

    /// Whom a read or write through `handle` is attributed to: the opener
    /// (`Attrib::Handle`) when the request has no usable caller of its own,
    /// else the caller.
    fn io_subject(
        &self,
        ctx: &Context,
        opener: Option<Subject>,
        by_kernel: bool,
    ) -> (Subject, Attrib) {
        match opener {
            Some(opener) if by_kernel || ctx.pid == 0 => (opener, Attrib::Handle),
            _ => (subject(ctx), Attrib::Caller),
        }
    }

    fn denied(&self, ctx: &Context, op: &str, path: PathText, errno: i32) {
        let payload = Payload::FsDenied(FsDenied {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            op: op.to_owned(),
            errno,
        });
        self.events.record(Some(subject(ctx)), payload);
    }

    /// Tracks a handle an open or create returned. Without one (a
    /// filesystem with zero-message opens) there is nothing to close.
    fn opened(&self, fh: u64, entry: HandleEntry) {
        if fh != 0 {
            self.handles.insert(fh, entry);
        }
    }

    /// Records the close of a handle the guest released, now or once it is
    /// hashed.
    fn close(&self, ctx: &Context, fh: u64, entry: HandleEntry) {
        let (subject, attrib) = if ctx.pid == 0 {
            (entry.opener, Attrib::Handle)
        } else {
            (subject(ctx), Attrib::Caller)
        };
        self.record_close(fh, entry, subject, attrib);
    }

    /// Closes every handle still open, as the guest's filesystem goes away
    /// (unmount, a driver unbind, a guest panic, the VM stopping) without
    /// releasing them, and waits for their hashes. At the normal level the
    /// close is the only record of what was written through a handle, so
    /// none may be dropped. There is no request, so each close is
    /// attributed to the handle's opener.
    fn close_open_handles(&self) {
        for (fh, entry) in self.handles.drain() {
            let opener = entry.opener;
            self.record_close(fh, entry, opener, Attrib::Handle);
        }
        self.hasher.flush();
    }

    /// Records `entry`'s close as `subject`: at once when nothing needs
    /// hashing, else once the hash worker has hashed the file.
    fn record_close(&self, fh: u64, entry: HandleEntry, subject: Subject, attrib: Attrib) {
        if self.events.log_failed() {
            // Nothing is recorded any more; the file need not be read.
            return;
        }
        // The producer's time: the release is now, whenever the hash that
        // completes the record is made.
        let ts_release_ns = realtime_ns();
        let (path, rel_path, deleted, expected) = {
            let paths = self.read_paths();
            (
                paths.path_text(entry.ino),
                paths.relative_path(entry.ino),
                paths.is_deleted(entry.ino),
                paths.host_id(entry.ino),
            )
        };
        let changed = entry.changed();
        let close = FsClose {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            path_at_open: entry.path_at_open,
            fh,
            bytes_read: entry.bytes_read,
            bytes_written: entry.bytes_written,
            size: None,
            blake3: None,
            hash_status: HashStatus::NotHashed,
            open_seq: entry.open_seq,
            attrib,
            ts_release_ns,
        };
        let status = if !changed {
            HashStatus::NotHashed
        } else if deleted {
            HashStatus::Gone
        } else {
            match rel_path.map(CString::new) {
                Some(Ok(rel_path)) => {
                    // Watched from the close, before any later change can
                    // reach the file.
                    let watch = self.generations.watch(FileKey::of(entry.ino, expected));
                    self.hasher.submit(HashJob {
                        rel_path,
                        expected,
                        subject,
                        close,
                        watch: Some(watch),
                    });
                    return;
                }
                // The path is not fully known, so the file cannot be found.
                _ => HashStatus::Error,
            }
        };
        let close = FsClose {
            hash_status: status,
            ..close
        };
        self.events.record(Some(subject), Payload::FsClose(close));
    }
}

/// The host identity in a reply's attributes.
fn host_id(attr: &stat64) -> FileId {
    FileId {
        dev: attr.st_dev,
        ino: attr.st_ino,
    }
}

/// Whether an open's access mode lets the handle write: anything but
/// `O_RDONLY` (mode 3, "no access", counts as writing).
fn opens_for_writing(flags: u32) -> bool {
    flags as libc::c_int & libc::O_ACCMODE != libc::O_RDONLY
}

/// The mode a node is created with.
fn effective_mode(mode: u32, umask: u32) -> u32 {
    mode & !(umask & 0o777)
}

/// Seconds since the epoch of a `setattr` time: the time asked for, or, for
/// "now", the time the reply reports (or the clock, if it failed).
fn set_time(asked: i64, now: bool, reply: Option<i64>) -> i64 {
    if !now {
        return asked;
    }
    reply.unwrap_or_else(|| {
        let since = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or(Duration::ZERO);
        i64::try_from(since.as_secs()).unwrap_or(i64::MAX)
    })
}

/// The fields a `setattr` asked to change.
fn set_attrs(attr: &stat64, valid: SetattrValid, reply: Option<&stat64>) -> SetAttr {
    let has = |bit: SetattrValid| valid.contains(bit);
    SetAttr {
        mode: has(SetattrValid::MODE).then_some(attr.st_mode & 0o7777),
        uid: has(SetattrValid::UID).then_some(attr.st_uid),
        gid: has(SetattrValid::GID).then_some(attr.st_gid),
        size: has(SetattrValid::SIZE).then(|| u64::try_from(attr.st_size).unwrap_or(0)),
        atime: has(SetattrValid::ATIME).then(|| {
            set_time(
                attr.st_atime,
                has(SetattrValid::ATIME_NOW),
                reply.map(|r| r.st_atime),
            )
        }),
        mtime: has(SetattrValid::MTIME).then(|| {
            set_time(
                attr.st_mtime,
                has(SetattrValid::MTIME_NOW),
                reply.map(|r| r.st_mtime),
            )
        }),
    }
}

impl<F: FileSystem<Inode = u64, Handle = u64>> Drop for AuditFs<F> {
    fn drop(&mut self) {
        self.shutdown();
    }
}

impl<F: FileSystem<Inode = u64, Handle = u64>> FileSystem for AuditFs<F> {
    type Inode = u64;
    type Handle = u64;

    forward! {
        init: audited,
        destroy: audited,
        lookup: audited,
        forget: audited,
        batch_forget: audited,
        getattr: forward,
        setattr: audited,
        readlink: forward,
        symlink: audited,
        mknod: audited,
        mkdir: audited,
        unlink: audited,
        rmdir: audited,
        rename: audited,
        link: audited,
        open: audited,
        create: audited,
        read: audited,
        write: audited,
        flush: forward,
        fsync: forward,
        fallocate: audited,
        release: audited,
        statfs: forward,
        setxattr: audited,
        getxattr: forward,
        listxattr: forward,
        removexattr: audited,
        opendir: forward,
        readdir: audited,
        readdirplus: audited,
        fsyncdir: forward,
        releasedir: forward,
        setupmapping: forward,
        removemapping: forward,
        access: audited,
        lseek: forward,
        getlk: forward,
        setlk: forward,
        setlkw: forward,
        ioctl: forward,
        bmap: forward,
        poll: forward,
        notify_reply: forward,
        id_remap: forward,
    }

    fn init(&self, capable: FsOptions) -> io::Result<FsOptions> {
        let wanted = self.inner.init(capable - MASKED_OPTIONS)? - MASKED_OPTIONS;
        let mount = Payload::FsMount(FsMount {
            mount: self.events.mount(),
            guest_path: self.guest_path.clone(),
            host_root: self.host_root.clone(),
            cache_policy: self.cache_policy.to_owned(),
        });
        self.events.record(None, mount);
        Ok(wanted)
    }

    fn destroy(&self) {
        // The guest's filesystem is going away: its open handles are closed
        // (and hashed) while the paths and the files are still there.
        self.close_open_handles();
        self.inner.destroy();
        // The guest holds no inodes any more.
        self.write_paths().reset();
    }

    fn lookup(&self, ctx: &Context, parent: u64, name: &CStr) -> io::Result<Entry> {
        let result = self.inner.lookup(&squash(ctx), parent, name);
        match &result {
            Ok(entry) => self.remember(parent, name.to_bytes(), entry),
            Err(e) => {
                let errno = errno(e);
                let refused = errno == libc::EACCES || errno == libc::EPERM;
                if refused || (self.verbose() && errno == libc::ENOENT) {
                    self.denied(ctx, "lookup", self.child(parent, name), errno);
                }
            }
        }
        result
    }

    fn forget(&self, ctx: &Context, inode: u64, count: u64) {
        self.inner.forget(&squash(ctx), inode, count);
        self.write_paths().forget(inode, count);
    }

    fn batch_forget(&self, ctx: &Context, requests: Vec<(u64, u64)>) {
        {
            let mut paths = self.write_paths();
            for &(inode, count) in &requests {
                paths.forget(inode, count);
            }
        }
        self.inner.batch_forget(&squash(ctx), requests);
    }

    fn setattr(
        &self,
        ctx: &Context,
        inode: u64,
        attr: stat64,
        handle: Option<u64>,
        valid: SetattrValid,
    ) -> io::Result<(stat64, Duration)> {
        self.refuse_if_log_failed()?;
        let path = self.path(inode);
        let result = self.inner.setattr(&squash(ctx), inode, attr, handle, valid);
        if result.is_ok() && valid.contains(SetattrValid::SIZE) {
            self.content_changed(inode);
            if let Some(fh) = handle {
                self.handles.update(fh, |e| e.truncated = true);
            }
        }
        let reply = result.as_ref().ok().map(|(st, _)| st);
        let payload = Payload::FsSetattr(FsSetattr {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            set: set_attrs(&attr, valid, reply),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn symlink(
        &self,
        ctx: &Context,
        linkname: &CStr,
        parent: u64,
        name: &CStr,
    ) -> io::Result<Entry> {
        self.refuse_if_log_failed()?;
        let path = self.child(parent, name);
        let result = self.inner.symlink(&squash(ctx), linkname, parent, name);
        if let Ok(entry) = &result {
            self.remember(parent, name.to_bytes(), entry);
        }
        let payload = Payload::FsSymlink(FsSymlink {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            target: c_text(linkname),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn mknod(
        &self,
        ctx: &Context,
        inode: u64,
        name: &CStr,
        mode: u32,
        rdev: u32,
        umask: u32,
    ) -> io::Result<Entry> {
        self.refuse_if_log_failed()?;
        let path = self.child(inode, name);
        let result = self
            .inner
            .mknod(&squash(ctx), inode, name, mode, rdev, umask);
        if let Ok(entry) = &result {
            self.remember(inode, name.to_bytes(), entry);
        }
        let payload = Payload::FsMknod(FsMknod {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            mode: effective_mode(mode, umask),
            rdev,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn mkdir(
        &self,
        ctx: &Context,
        parent: u64,
        name: &CStr,
        mode: u32,
        umask: u32,
    ) -> io::Result<Entry> {
        self.refuse_if_log_failed()?;
        let path = self.child(parent, name);
        let result = self.inner.mkdir(&squash(ctx), parent, name, mode, umask);
        if let Ok(entry) = &result {
            self.remember(parent, name.to_bytes(), entry);
        }
        let payload = Payload::FsMkdir(FsMkdir {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            mode: effective_mode(mode, umask),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn unlink(&self, ctx: &Context, parent: u64, name: &CStr) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let path = self.child(parent, name);
        let result = self.inner.unlink(&squash(ctx), parent, name);
        if result.is_ok() {
            self.write_paths().mark_deleted(parent, name.to_bytes());
        }
        let payload = Payload::FsUnlink(FsPathOp {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn rmdir(&self, ctx: &Context, parent: u64, name: &CStr) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let path = self.child(parent, name);
        let result = self.inner.rmdir(&squash(ctx), parent, name);
        if result.is_ok() {
            self.write_paths().mark_deleted(parent, name.to_bytes());
        }
        let payload = Payload::FsRmdir(FsPathOp {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn rename(
        &self,
        ctx: &Context,
        olddir: u64,
        oldname: &CStr,
        newdir: u64,
        newname: &CStr,
        flags: u32,
    ) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let from = self.child(olddir, oldname);
        let to = self.child(newdir, newname);
        let result = self
            .inner
            .rename(&squash(ctx), olddir, oldname, newdir, newname, flags);
        if result.is_ok() {
            let (old, new) = (oldname.to_bytes(), newname.to_bytes());
            let mut paths = self.write_paths();
            if flags & libc::RENAME_EXCHANGE != 0 {
                paths.exchange(olddir, old, newdir, new);
            } else {
                paths.rename(olddir, old, newdir, new);
            }
        }
        let payload = Payload::FsRename(FsRename {
            mount: self.events.mount(),
            from: from.path,
            to: to.path,
            flags,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn link(&self, ctx: &Context, inode: u64, newparent: u64, newname: &CStr) -> io::Result<Entry> {
        self.refuse_if_log_failed()?;
        let target_path = self.path(inode).path;
        let path = self.child(newparent, newname);
        let result = self.inner.link(&squash(ctx), inode, newparent, newname);
        if let Ok(entry) = &result {
            self.remember(newparent, newname.to_bytes(), entry);
        }
        let payload = Payload::FsLink(FsLink {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            target_path,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn open(
        &self,
        ctx: &Context,
        inode: u64,
        flags: u32,
        fuse_flags: u32,
    ) -> io::Result<(Option<u64>, OpenOptions, Option<u32>)> {
        let truncates = flags & libc::O_TRUNC as u32 != 0;
        if opens_for_writing(flags) || truncates {
            self.refuse_if_log_failed()?;
        }
        let path = self.path(inode);
        let result = self.inner.open(&squash(ctx), inode, flags, fuse_flags);
        let fh = match &result {
            Ok((handle, _, _)) => handle.unwrap_or(0),
            Err(_) => 0,
        };
        if result.is_ok() && truncates {
            self.content_changed(inode);
        }
        if result.is_ok() {
            let entry = HandleEntry {
                ino: inode,
                path_at_open: path.path.clone(),
                flags,
                opener: subject(ctx),
                open_seq: None,
                bytes_read: 0,
                bytes_written: 0,
                wrote: false,
                created: false,
                truncated: truncates,
            };
            self.opened(fh, entry);
        }
        let payload = Payload::FsOpen(FsOpen {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            fh,
            flags,
            flags_decoded: decode_open_flags(flags),
            exec: is_exec(flags),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn create(
        &self,
        ctx: &Context,
        parent: u64,
        name: &CStr,
        args: CreateIn,
    ) -> io::Result<(Entry, Option<u64>, OpenOptions, Option<u32>)> {
        self.refuse_if_log_failed()?;
        let path = self.child(parent, name);
        let result = self.inner.create(&squash(ctx), parent, name, args);
        let fh = match &result {
            Ok((_, handle, _, _)) => handle.unwrap_or(0),
            Err(_) => 0,
        };
        if let Ok((entry, _, _, _)) = &result {
            self.remember(parent, name.to_bytes(), entry);
            // Creating an existing file without O_EXCL opens it, and may
            // truncate it.
            self.content_changed(entry.inode);
            let handle = HandleEntry {
                ino: entry.inode,
                path_at_open: path.path.clone(),
                flags: args.flags,
                opener: subject(ctx),
                open_seq: None,
                bytes_read: 0,
                bytes_written: 0,
                wrote: false,
                created: true,
                truncated: args.flags & libc::O_TRUNC as u32 != 0,
            };
            self.opened(fh, handle);
        }
        let payload = Payload::FsCreate(FsCreate {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            fh,
            mode: effective_mode(args.mode, args.umask),
            flags: args.flags,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn read(
        &self,
        ctx: &Context,
        inode: u64,
        handle: u64,
        w: &mut dyn ZeroCopyWriter,
        size: u32,
        offset: u64,
        lock_owner: Option<u64>,
        flags: u32,
    ) -> io::Result<usize> {
        let result = self.inner.read(
            &squash(ctx),
            inode,
            handle,
            w,
            size,
            offset,
            lock_owner,
            flags,
        );
        let done = result.as_ref().map_or(0, |&n| n as u64);
        let opener = self.handles.update(handle, |e| {
            e.bytes_read = e.bytes_read.saturating_add(done);
            e.opener
        });
        if self.verbose() {
            let len = match &result {
                Ok(n) => u32::try_from(*n).unwrap_or(u32::MAX),
                Err(_) => size,
            };
            let (who, attrib) = self.io_subject(ctx, opener, false);
            let path = self.path(inode);
            let payload = Payload::FsRead(FsIo {
                mount: self.events.mount(),
                path: path.path,
                path_b64: path.path_b64,
                fh: handle,
                offset,
                len,
                result: op_result(&result),
                attrib,
            });
            self.events.sample(Some(who), payload);
        }
        result
    }

    fn write(
        &self,
        ctx: &Context,
        inode: u64,
        handle: u64,
        r: &mut dyn ZeroCopyReader,
        size: u32,
        offset: u64,
        lock_owner: Option<u64>,
        delayed_write: bool,
        flags: u32,
        fuse_flags: u32,
    ) -> io::Result<usize> {
        self.refuse_if_log_failed()?;
        let result = self.inner.write(
            &squash(ctx),
            inode,
            handle,
            r,
            size,
            offset,
            lock_owner,
            delayed_write,
            flags,
            fuse_flags,
        );
        let done = result.as_ref().map_or(0, |&n| n as u64);
        if done > 0 {
            self.content_changed(inode);
        }
        let opener = self.handles.update(handle, |e| {
            e.bytes_written = e.bytes_written.saturating_add(done);
            e.wrote |= done > 0;
            e.opener
        });
        if self.verbose() {
            let len = match &result {
                Ok(n) => u32::try_from(*n).unwrap_or(u32::MAX),
                Err(_) => size,
            };
            // A write-back from the guest's page cache is made by whichever
            // thread flushes it, not by the process that wrote the data.
            let cached = delayed_write || fuse_flags & WRITE_CACHE != 0;
            let (who, attrib) = self.io_subject(ctx, opener, cached);
            let path = self.path(inode);
            let payload = Payload::FsWrite(FsIo {
                mount: self.events.mount(),
                path: path.path,
                path_b64: path.path_b64,
                fh: handle,
                offset,
                len,
                result: op_result(&result),
                attrib,
            });
            self.events.sample(Some(who), payload);
        }
        result
    }

    fn fallocate(
        &self,
        ctx: &Context,
        inode: u64,
        handle: u64,
        mode: u32,
        offset: u64,
        length: u64,
    ) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let path = self.path(inode);
        let result = self
            .inner
            .fallocate(&squash(ctx), inode, handle, mode, offset, length);
        if result.is_ok() {
            // Allocating past the end, punching a hole or zeroing a range
            // all change what the file reads as.
            self.content_changed(inode);
            self.handles.update(handle, |e| e.wrote = true);
        }
        let payload = Payload::FsFallocate(FsFallocate {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            offset,
            len: length,
            mode,
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn release(
        &self,
        ctx: &Context,
        inode: u64,
        flags: u32,
        handle: u64,
        flush: bool,
        flock_release: bool,
        lock_owner: Option<u64>,
    ) -> io::Result<()> {
        let result = self.inner.release(
            &squash(ctx),
            inode,
            flags,
            handle,
            flush,
            flock_release,
            lock_owner,
        );
        // The kernel ignores the reply to a release: the handle is gone
        // either way.
        if let Some(entry) = self.handles.take(handle) {
            self.close(ctx, handle, entry);
        }
        result
    }

    fn setxattr(
        &self,
        ctx: &Context,
        inode: u64,
        name: &CStr,
        value: &[u8],
        flags: u32,
    ) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let path = self.path(inode);
        let result = self.inner.setxattr(&squash(ctx), inode, name, value, flags);
        let payload = Payload::FsXattr(FsXattr {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            name: c_text(name),
            op: "set".to_owned(),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn removexattr(&self, ctx: &Context, inode: u64, name: &CStr) -> io::Result<()> {
        self.refuse_if_log_failed()?;
        let path = self.path(inode);
        let result = self.inner.removexattr(&squash(ctx), inode, name);
        let payload = Payload::FsXattr(FsXattr {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            name: c_text(name),
            op: "remove".to_owned(),
            result: op_result(&result),
        });
        self.events.record(Some(subject(ctx)), payload);
        result
    }

    fn readdir(
        &self,
        ctx: &Context,
        inode: u64,
        handle: u64,
        size: u32,
        offset: u64,
        add_entry: &mut dyn FnMut(DirEntry) -> io::Result<usize>,
    ) -> io::Result<()> {
        let result = self
            .inner
            .readdir(&squash(ctx), inode, handle, size, offset, add_entry);
        if self.verbose() {
            self.listed(ctx, inode, &result);
        }
        result
    }

    fn readdirplus(
        &self,
        ctx: &Context,
        inode: u64,
        handle: u64,
        size: u32,
        offset: u64,
        add_entry: &mut dyn FnMut(DirEntry, Entry) -> io::Result<usize>,
    ) -> io::Result<()> {
        // The kernel counts a lookup for every entry that makes it into the
        // reply, except `.` and `..`, and forgets them later like any other.
        let mut returned: Vec<(Box<[u8]>, Entry)> = Vec::new();
        let result = self.inner.readdirplus(
            &squash(ctx),
            inode,
            handle,
            size,
            offset,
            &mut |dirent, entry| {
                let added = add_entry(dirent, entry)?;
                // 0: the reply is full and the entry was not added.
                if added > 0 && dirent.name != b"." && dirent.name != b".." {
                    returned.push((dirent.name.into(), entry));
                }
                Ok(added)
            },
        );
        // An error reply carries no entries.
        if result.is_ok() && !returned.is_empty() {
            let mut paths = self.write_paths();
            for (name, entry) in &returned {
                paths.insert(inode, name, entry.inode);
                paths.set_host_id(entry.inode, host_id(&entry.attr));
            }
        }
        if self.verbose() {
            self.listed(ctx, inode, &result);
        }
        result
    }

    fn access(&self, ctx: &Context, inode: u64, mask: u32) -> io::Result<()> {
        let result = self.inner.access(&squash(ctx), inode, mask);
        if let Err(e) = &result {
            if errno(e) == libc::EACCES {
                self.denied(ctx, "access", self.path(inode), libc::EACCES);
            }
        }
        result
    }
}

impl<F: FileSystem<Inode = u64, Handle = u64>> AuditFs<F> {
    /// `fs.readdir`, at the verbose level.
    fn listed(&self, ctx: &Context, inode: u64, result: &io::Result<()>) {
        let path = self.path(inode);
        let payload = Payload::FsReaddir(FsPathOp {
            mount: self.events.mount(),
            path: path.path,
            path_b64: path.path_b64,
            result: op_result(result),
        });
        self.events.sample(Some(subject(ctx)), payload);
    }
}

#[cfg(test)]
mod tests {
    use std::fs::{self, File};
    use std::io::{Seek, SeekFrom, Write};
    use std::sync::{Condvar, Mutex};

    use boxcar_audit::{spawn, LogReader, WriterConfig};
    use boxcar_proto::SessionId;
    use fuse_backend_rs::api::filesystem::ROOT_ID;
    use fuse_backend_rs::passthrough::PassthroughFs;
    use tempfile::TempDir;

    use super::*;
    use crate::share::{passthrough_config, CachePolicyKind};

    static GATE: Mutex<bool> = Mutex::new(false);
    static GATE_OPENED: Condvar = Condvar::new();

    /// Waits until the gate opens, then hashes as in production.
    fn hash_after_the_gate(
        root: &OwnedFd,
        rel_path: &CString,
        expected: Option<FileId>,
        max: u64,
    ) -> crate::hasher::HashOutcome {
        let mut open = GATE.lock().unwrap();
        while !*open {
            open = GATE_OPENED.wait(open).unwrap();
        }
        drop(open);
        hash_file(root, rel_path, expected, max)
    }

    fn payload(data: &[u8]) -> File {
        let mut file = tempfile::tempfile().unwrap();
        file.write_all(data).unwrap();
        file.seek(SeekFrom::Start(0)).unwrap();
        file
    }

    const GUEST: Context = Context {
        uid: 1000,
        gid: 1000,
        pid: 42,
    };

    /// The content the first close hashed is the content its handle left
    /// behind, or it is `raced`: a write through another handle after the
    /// close, before the queued hash runs, is not the closer's.
    #[test]
    fn a_write_after_the_close_before_the_hash_makes_it_raced() {
        let dir = TempDir::new().unwrap();
        let root = dir.path().join("share");
        fs::create_dir(&root).unwrap();
        let (sink, writer) =
            spawn(WriterConfig::new(dir.path().join("data"), SessionId::new())).unwrap();
        let share = FsShareConfig {
            tag: "workspace".into(),
            host_dir: root.clone(),
            guest_path: "/workspace".into(),
            cache: CachePolicyKind::Auto,
        };
        let inner = PassthroughFs::<()>::new(passthrough_config(&share)).unwrap();
        inner.import().unwrap();
        let root_fd = OwnedFd::from(File::open(&root).unwrap());
        let fs = AuditFs::with_hash(
            inner,
            &share,
            root_fd,
            sink,
            AuditFsOptions::default(),
            hash_after_the_gate,
        );
        let rw = (libc::O_RDWR | libc::O_CREAT) as u32;
        let args = CreateIn {
            flags: rw,
            mode: libc::S_IFREG | 0o644,
            umask: 0o022,
            fuse_flags: 0,
        };
        let write = |ino, fh, data: &[u8]| {
            let size = data.len() as u32;
            fs.write(
                &GUEST,
                ino,
                fh,
                &mut payload(data),
                size,
                0,
                None,
                false,
                rw,
                0,
            )
            .unwrap()
        };

        let name = CString::new("f").unwrap();
        let (entry, first, _, _) = fs.create(&GUEST, ROOT_ID, &name, args).unwrap();
        let (ino, first) = (entry.inode, first.unwrap());
        write(ino, first, b"one");
        // The close's hash waits behind the gate.
        fs.release(&GUEST, ino, rw, first, false, false, None)
            .unwrap();
        let (second, _, _) = fs.open(&GUEST, ino, libc::O_RDWR as u32, 0).unwrap();
        let second = second.unwrap();
        write(ino, second, b"two!");
        *GATE.lock().unwrap() = true;
        GATE_OPENED.notify_all();
        fs.release(&GUEST, ino, rw, second, false, false, None)
            .unwrap();
        fs.flush_hashes();

        let session = writer.session_dir().to_owned();
        drop(fs);
        writer.close().unwrap();
        let closes: Vec<FsClose> = LogReader::open(&session)
            .unwrap()
            .records()
            .filter_map(|r| match Payload::from_record(&r.unwrap()) {
                Ok(Payload::FsClose(c)) => Some(c),
                _ => None,
            })
            .collect();
        let of = |fh| closes.iter().find(|c| c.fh == fh).expect("a close");
        let (first, second) = (of(first), of(second));
        assert_eq!(first.hash_status, HashStatus::Raced, "{first:?}");
        assert_eq!(first.blake3, None, "{first:?}");
        assert_eq!(second.hash_status, HashStatus::Ok, "{second:?}");
        assert_eq!(
            second.blake3,
            Some(boxcar_proto::Hash::from_blake3(blake3::hash(b"two!")))
        );
    }

    /// A hash function that panics, as a bug in one would.
    fn panicking_hash(
        _: &OwnedFd,
        _: &CString,
        _: Option<FileId>,
        _: u64,
    ) -> crate::hasher::HashOutcome {
        panic!("the hash function failed");
    }

    /// A hash thread that panics on a job still records that job's close,
    /// as `error` with no hash. (One job for each of the two threads: with
    /// both gone, a third would be hashed on this thread, and panic here.)
    #[test]
    fn a_hash_job_that_panics_records_an_error_close() {
        let dir = TempDir::new().unwrap();
        let root = dir.path().join("share");
        fs::create_dir(&root).unwrap();
        let (sink, writer) =
            spawn(WriterConfig::new(dir.path().join("data"), SessionId::new())).unwrap();
        let share = FsShareConfig {
            tag: "workspace".into(),
            host_dir: root.clone(),
            guest_path: "/workspace".into(),
            cache: CachePolicyKind::Auto,
        };
        let inner = PassthroughFs::<()>::new(passthrough_config(&share)).unwrap();
        inner.import().unwrap();
        let root_fd = OwnedFd::from(File::open(&root).unwrap());
        let fs = AuditFs::with_hash(
            inner,
            &share,
            root_fd,
            sink,
            AuditFsOptions::default(),
            panicking_hash,
        );
        let rw = (libc::O_RDWR | libc::O_CREAT) as u32;
        let args = CreateIn {
            flags: rw,
            mode: libc::S_IFREG | 0o644,
            umask: 0o022,
            fuse_flags: 0,
        };
        // Quiet: the panics below are the test's.
        let hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(|_| {}));
        let mut handles = Vec::new();
        for n in 0..2 {
            let name = CString::new(format!("f{n}")).unwrap();
            let (entry, fh, _, _) = fs.create(&GUEST, ROOT_ID, &name, args).unwrap();
            let fh = fh.unwrap();
            let size = 3;
            fs.write(
                &GUEST,
                entry.inode,
                fh,
                &mut payload(b"abc"),
                size,
                0,
                None,
                false,
                rw,
                0,
            )
            .unwrap();
            fs.release(&GUEST, entry.inode, rw, fh, false, false, None)
                .unwrap();
            handles.push(fh);
        }
        fs.flush_hashes();
        std::panic::set_hook(hook);

        let session = writer.session_dir().to_owned();
        drop(fs);
        writer.close().unwrap();
        let closes: Vec<FsClose> = LogReader::open(&session)
            .unwrap()
            .records()
            .filter_map(|r| match Payload::from_record(&r.unwrap()) {
                Ok(Payload::FsClose(c)) => Some(c),
                _ => None,
            })
            .collect();
        let mut recorded: Vec<u64> = closes.iter().map(|c| c.fh).collect();
        recorded.sort_unstable();
        handles.sort_unstable();
        assert_eq!(recorded, handles, "every close is recorded");
        for close in &closes {
            assert_eq!(close.hash_status, HashStatus::Error, "{close:?}");
            assert_eq!((close.size, close.blake3), (None, None));
            assert_eq!(close.bytes_written, 3);
            assert!(close.ts_release_ns > 0);
        }
    }

    fn zero_stat() -> stat64 {
        // SAFETY: stat64 is plain data; all-zero is a valid value.
        unsafe { std::mem::zeroed() }
    }

    #[test]
    fn only_the_valid_fields_are_recorded() {
        let mut attr = zero_stat();
        attr.st_mode = libc::S_IFREG | 0o4755;
        attr.st_uid = 7;
        attr.st_gid = 8;
        attr.st_size = 99;
        attr.st_atime = 1000;
        attr.st_mtime = 2000;
        let all = SetattrValid::MODE
            | SetattrValid::UID
            | SetattrValid::GID
            | SetattrValid::SIZE
            | SetattrValid::ATIME
            | SetattrValid::MTIME;
        assert_eq!(
            set_attrs(&attr, all, None),
            SetAttr {
                mode: Some(0o4755),
                uid: Some(7),
                gid: Some(8),
                size: Some(99),
                atime: Some(1000),
                mtime: Some(2000),
            }
        );
        assert_eq!(
            set_attrs(&attr, SetattrValid::empty(), None),
            SetAttr::default()
        );
    }

    #[test]
    fn now_times_come_from_the_reply() {
        let attr = zero_stat();
        let mut reply = zero_stat();
        reply.st_mtime = 1_800_000_000;
        let valid = SetattrValid::MTIME | SetattrValid::MTIME_NOW;
        assert_eq!(
            set_attrs(&attr, valid, Some(&reply)).mtime,
            Some(1_800_000_000)
        );
        let clock = set_attrs(&attr, valid, None).mtime.unwrap();
        assert!(clock > 1_700_000_000, "falls back to the clock: {clock}");
    }

    #[test]
    fn modes_are_masked_by_the_umask() {
        assert_eq!(effective_mode(0o777, 0o022), 0o755);
        assert_eq!(
            effective_mode(libc::S_IFIFO | 0o666, 0o027),
            libc::S_IFIFO | 0o640
        );
        assert_eq!(
            effective_mode(0o644, 0o7000),
            0o644,
            "only permission bits mask"
        );
    }

    #[test]
    fn the_masked_options_are_writeback_and_dax() {
        assert!(MASKED_OPTIONS.contains(FsOptions::WRITEBACK_CACHE));
        assert!(MASKED_OPTIONS.contains(FsOptions::MAP_ALIGNMENT));
        assert!(MASKED_OPTIONS.contains(FsOptions::PERFILE_DAX));
        assert!(!MASKED_OPTIONS.contains(FsOptions::DO_READDIRPLUS));
    }
}
