// SPDX-License-Identifier: MIT OR GPL-2.0
// Copyright 2026 The boxcar Authors

//! The guest sensor's eBPF programs. The object this builds to is loaded by
//! `boxcar-sensor` in the guest; its `license` section is `Dual MIT/GPL` so
//! the kernel lets it use the GPL-only helpers and the LSM hooks. The
//! programs come with Task 3 of the M3 plan; the kernel types they read are
//! `vmlinux`, generated by `cargo xtask gen-vmlinux`.

#![no_std]
#![no_main]

#[rustfmt::skip]
mod vmlinux;

/// The target has no unwinding; the verifier rejects a program in which this
/// is reachable, so no program may panic.
#[cfg(not(test))]
#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    loop {}
}

#[link_section = "license"]
#[no_mangle]
static LICENSE: [u8; 13] = *b"Dual MIT/GPL\0";
